export const ADD_BOOKMARK = `ADD_BOOKMARK`;
export const REMOVE_BOOKMARK = `REMOVE_BOOKMARK`;
export const UPDATE_BOOKMARK = `UPDATE_BOOKMARK`;
export const READ_BOOKMARK = `READ_BOOKMARK`;
export const UPDATE_LOADING = `UPDATE_LOADING`;
export const FETCH_DATA_SUCCESS = `FETCH_DATA_SUCCESS`;
export const FETCH_DATA_FAILURE = `FETCH_DATA_FAILURE`;